### ISSUE TITLE
PKGBUILD fails to build without removing "src"

### ISSUE THREAD

**Issue by telans** [ungoogled-software/ungoogled-chromium-archlinux#60]
Looks like leftover files, not sure if this just applies to the pkgbuild.

```
The next patch would create the file net/url_request/trk_protocol_handler.cc,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file net/url_request/trk_protocol_handler.h,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file net/url_request/url_request.cc
patching file net/url_request/url_request_context_builder.cc
patching file url/url_constants.cc
patching file url/url_constants.h
patching file url/url_util.cc
Traceback (most recent call last):
  File "/home/telans/ungoogled-chromium-archlinux/src/ungoogled-chromium/utils/patches.py", line 160, in <module>
    main()
  File "/home/telans/ungoogled-chromium-archlinux/src/ungoogled-chromium/utils/patches.py", line 156, in main
    args.callback(args)
  File "/home/telans/ungoogled-chromium-archlinux/src/ungoogled-chromium/utils/patches.py", line 110, in _apply_callback
    apply_patches(
  File "/home/telans/ungoogled-chromium-archlinux/src/ungoogled-chromium/utils/patches.py", line 54, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/sbin/patch', '-p1', '--ignore-whitespace', '-i', '/home/telans/ungoogled-chromium-archlinux/src/ungoogled-chromium/patches/core/ungoogled-chromium/block-trk-and-subdomains.patch', '-d', '.', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by braewoods** [comment]
Standard problem with ARCH afaik. They expect you to delete the source directory if the build fails or so.

**Comment by jstkdng** [comment]
It fails because it is trying to patch something which was already patched, removing the src directory solves the problem.
If you want to rebuild without patching just use `makepkg -e --noprepare`

**Comment by wchen342** [comment]
Or, what I always does is using `makepkg -sirc` which will install dependencies and clean up for you after the build.

**Comment by jstkdng** [comment]
I just manually delete the srcdir using rsync, as it is faster

**Comment by Eloston** [comment]
Question looks solved, closing.
