### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by SemtexError** [ungoogled-software/ungoogled-chromium-archlinux#61]
I've been getting the 'No such file or directory' error for a while on both my desktop and laptop.

```
[4908/37483] ACTION //third_party/blink/renderer/core:make_core_generated_bison(//build/toolchain/linux/unbundle:default)
FAILED: gen/third_party/blink/renderer/core/xpath_grammar.cc gen/third_party/blink/renderer/core/xpath_grammar.h 
/usr/bin/python2 ../../third_party/blink/renderer/build/scripts/rule_bison.py ../../third_party/blink/renderer/core/xml/xpath_grammar.y gen/third_party/blink/renderer/core bison
Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/rule_bison.py", line 83, in <module>
    returnCode = subprocess.call([bisonExe, '-d', '-p', prefix, inputFile, '-o', outputCpp])
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[4909/37483] CC obj/third_party/boringssl/boringssl/a_print.o
[4910/37483] ACTION //third_party/blink/renderer/core:make_core_generated_xml_ns_names(//build/toolchain/linux/unbundle:default)
[4911/37483] ACTION //third_party/blink/renderer/core:make_core_generated_input_type_names(//build/toolchain/linux/unbundle:default)
[4912/37483] ACTION //third_party/blink/renderer/core:make_core_generated_keywords(//build/toolchain/linux/unbundle:default)
[4913/37483] CXX obj/third_party/blink/public/mojom/web_feature_mojo_bindings_shared_cpp_sources/css_property_id.mojom-shared.o
[4914/37483] ACTION //third_party/blink/renderer/core:make_core_generated_css_value_id_mappings(//build/toolchain/linux/unbundle:default)
[4915/37483] ACTION //third_party/blink/renderer/core/inspector:protocol_sources(//build/toolchain/linux/unbundle:default)
[4916/37483] CXX obj/third_party/blink/public/mojom/web_feature_mojo_bindings_shared_cpp_sources/web_feature.mojom-shared.o
[4917/37483] CXX obj/third_party/blink/public/mojom/web_bluetooth_mojo_bindings/web_bluetooth.mojom.o
ninja: build stopped: subcommand failed.

```

Full log [here](https://gist.github.com/SemtexError/641fc292101e286ac42505eb3bdab0d2)

**Comment by wchen342** [comment]
Do you have `base-devel` group installed? Try install the group with `pacman` and do the make again.

**Comment by SemtexError** [comment]
I though I had but apparently I was missing a packages.
I'm sorry for wasting your time.
